#!/bin/bash
# ==============================================================================
# RCA 1802/1806 Chess Engine - Build Script
# ==============================================================================
# Preprocess, concatenate, and assemble all modules
# ==============================================================================

echo "RCA 1802/1806 Chess Engine - Build Script"
echo "=========================================="
echo ""

# Output files
OUTPUT="chess-engine.asm"
PREPROCESSED="chess-engine-pp.asm"
HEXFILE="chess-engine.hex"

echo "Step 1: Preprocessing configuration..."

# Check if cpp is available
if ! command -v cpp &> /dev/null; then
    echo "  WARNING: cpp (C preprocessor) not found!"
    echo "  Conditional compilation will not work."
    echo "  Install gcc or use the preprocessed files directly."
    echo ""
fi

# Preprocess config.asm to handle #define/#ifdef directives
if command -v cpp &> /dev/null; then
    echo "  - Preprocessing config.asm with cpp..."
    # Use cpp with options:
    #   -P: Don't generate line markers
    #   -traditional: Traditional mode (better for assembly)
    #   -nostdinc: Don't search standard include paths
    #   -undef: Don't predefine system macros
    cpp -P -traditional -nostdinc -undef config.asm > config-preprocessed.asm 2>/dev/null

    if [ $? -eq 0 ]; then
        echo "  - Preprocessing successful"
        CONFIG_FILE="config-preprocessed.asm"
    else
        echo "  - Preprocessing had errors, using original config.asm"
        CONFIG_FILE="config.asm"
    fi
else
    CONFIG_FILE="config.asm"
fi

echo ""
echo "Step 2: Concatenating modules in dependency order..."

# Remove old output if exists
rm -f "$OUTPUT" "$HEXFILE"

# Create header
cat > "$OUTPUT" << 'EOF'
; ==============================================================================
; RCA 1802/1806 Chess Engine - Complete Assembly
; ==============================================================================
; Auto-generated by build.sh
; Target: RCA 1806 @ 12 MHz, 32KB RAM
; ==============================================================================

    ORG $0000

; Entry point - jump to main program
    LBR START

EOF

# Include configuration first (defines build-time options)
echo "; ==============================================================================" >> "$OUTPUT"
echo "; Build Configuration (preprocessed)" >> "$OUTPUT"
echo "; ==============================================================================" >> "$OUTPUT"
echo "  - $CONFIG_FILE"
cat "$CONFIG_FILE" >> "$OUTPUT"

echo "" >> "$OUTPUT"
echo "; ==============================================================================" >> "$OUTPUT"
echo "; Module: Support Routines (16-bit arithmetic)" >> "$OUTPUT"
echo "; ==============================================================================" >> "$OUTPUT"

# Append modules in dependency order
# Skip SCRT in BIOS mode - BIOS already provides R4=CALL, R5=RET, R2=stack
if grep -q "^USE_BIOS.*EQU 1" "$CONFIG_FILE" 2>/dev/null; then
    echo "  - (skipping scrt.asm - BIOS provides SCRT)"
else
    echo "  - scrt.asm (Standard Call/Return Technique)"
    cat scrt.asm >> "$OUTPUT"
fi

# Include serial I/O EARLY to keep short branches in range
if grep -q "^USE_BIOS.*EQU 1" "$CONFIG_FILE" 2>/dev/null; then
    echo "  - serial-io.asm (BIOS mode - F_TYPE, F_READ, F_MSG)"
    cpp -P -DBIOS serial-io.asm >> "$OUTPUT"
elif grep -q "^USE_BITBANG.*EQU 1" "$CONFIG_FILE" 2>/dev/null; then
    echo "  - serial-io-9600.asm (9600 baud fixed timing - Chuck's routine)"
    cat serial-io-9600.asm >> "$OUTPUT"
elif grep -q "^USE_UART.*EQU 1" "$CONFIG_FILE" 2>/dev/null; then
    echo "  - serial-io-uart.asm (hardware UART)"
    cat serial-io-uart.asm >> "$OUTPUT"
else
    echo "  WARNING: No serial I/O module selected, using BIOS as default"
    cpp -P -DBIOS serial-io.asm >> "$OUTPUT"
fi

echo "  - support.asm"
cat support.asm >> "$OUTPUT"

echo "  - math.asm"
cat math.asm >> "$OUTPUT"

echo "  - stack.asm"
cat stack.asm >> "$OUTPUT"

echo "  - board-0x88.asm (0x88 board representation)"
cat board-0x88.asm >> "$OUTPUT"

echo "  - check.asm"
cat check.asm >> "$OUTPUT"

echo "  - movegen-helpers.asm"
cat movegen-helpers.asm >> "$OUTPUT"

echo "  - movegen-fixed.asm (integrated version)"
cat movegen-fixed.asm >> "$OUTPUT"

echo "  - makemove-helpers.asm"
cat makemove-helpers.asm >> "$OUTPUT"

echo "  - makemove.asm"
cat makemove.asm >> "$OUTPUT"

echo "  - evaluate.asm"
cat evaluate.asm >> "$OUTPUT"

echo "  - pst.asm (piece-square tables)"
cat pst.asm >> "$OUTPUT"

echo "  - endgame.asm (endgame heuristics)"
cat endgame.asm >> "$OUTPUT"

echo "  - negamax.asm (fixed - no stubs)"
cat negamax.asm >> "$OUTPUT"

echo "  - uci.asm"
cat uci.asm >> "$OUTPUT"

echo "  - opening-book-lookup.asm"
cat opening-book-lookup.asm >> "$OUTPUT"

echo "  - opening-book.asm (opening book data)"
cat opening-book.asm >> "$OUTPUT"

# Preprocess main.asm with -DBIOS in BIOS mode
if grep -q "^USE_BIOS.*EQU 1" "$CONFIG_FILE" 2>/dev/null; then
    echo "  - main.asm (BIOS mode)"
    cpp -P -DBIOS main.asm >> "$OUTPUT"
else
    echo "  - main.asm"
    cat main.asm >> "$OUTPUT"
fi

echo ""
echo "Step 3: Concatenation complete. Output: $OUTPUT"
echo "  File size: $(wc -l < "$OUTPUT") lines"
echo ""

# Check if assembler is available
if command -v asm1802 &> /dev/null; then
    echo "Step 4: Assembling with asm1802..."
    asm1802 "$OUTPUT" -o "$HEXFILE"

    if [ $? -eq 0 ]; then
        echo "  SUCCESS: $HEXFILE created"
        echo "  Size: $(wc -c < "$HEXFILE") bytes"
    else
        echo "  ERROR: Assembly failed"
        exit 1
    fi
elif command -v a18 &> /dev/null; then
    echo "Step 4: Assembling with a18..."
    a18 "$OUTPUT" -o "$HEXFILE" -l chess-engine.lst 2>&1 | grep -v "Error(s)" || true

    # Check if hex file was created (a18 creates it even with "errors")
    if [ -f "$HEXFILE" ] && [ -s "$HEXFILE" ]; then
        echo "  ✓ SUCCESS: $HEXFILE created"

        # Reformat hex file with 24-byte records (fits 64-char monitor input)
        if command -v srec_cat &> /dev/null; then
            srec_cat "$HEXFILE" -intel -o "$HEXFILE" -intel -line-length=57
            echo "  ✓ Reformatted with 24-byte records"
        fi

        echo "  Size: $(wc -c < "$HEXFILE") bytes"

        # Check for actual assembly errors (not forward references)
        ERRORS=$(grep "^[A-Z]" chess-engine.lst 2>/dev/null | wc -l)
        if [ "$ERRORS" -gt 0 ]; then
            echo "  ⚠ WARNING: $ERRORS assembly error(s) found:"
            grep "^[A-Z]" chess-engine.lst
        fi
    else
        echo "  ✗ ERROR: Assembly failed - no hex file generated"
        exit 1
    fi
else
    echo "Step 4: SKIPPED - No 1802 assembler found"
    echo "  Supported assemblers: asm1802, a18"
    echo "  You can manually assemble $OUTPUT with your assembler"
fi

echo ""
echo "Build complete!"
echo "=========================================="
echo ""
echo "Configuration used:"
if [ -f "config-preprocessed.asm" ]; then
    grep "^#define" config.asm | sed 's|/\*.*\*/||g'
else
    echo "  (No preprocessing - using config.asm as-is)"
fi
echo ""
echo "Next steps:"
echo "  1. If assembly succeeded, flash $HEXFILE to your RCA 1806 system"
echo "  2. To change configuration, edit config.asm and rebuild"
echo "  3. See INTEGRATION-GUIDE.md for testing procedures"
echo ""
