; Zobrist hash keys for transposition table
; Generated by gen_zobrist.py
; Seed: 0x1802CAFE
;
; Piece indices:
;   0-5:  White P, N, B, R, Q, K
;   6-11: Black P, N, B, R, Q, K
;
; Square indices: 0-63 (rank*8 + file)
;

; ===========================================
; Piece-Square Keys (768 x 2 bytes = 1536 bytes)
; Access: ZOBRIST_PIECE_SQ + (piece_index * 128) + (square * 2)
; ===========================================
ZOBRIST_PIECE_SQ:
; Piece 0: WhiteP
    DW $63C3, $C779, $3A3C, $7599  ; d1
    DW $3141, $C2D6, $D891, $CEC4  ; h1
    DW $83DE, $5B37, $5799, $E158  ; d2
    DW $89D7, $CA58, $6328, $A9A0  ; h2
    DW $BD96, $9419, $14B7, $2BBB  ; d3
    DW $CA09, $EC60, $3309, $E193  ; h3
    DW $C7DB, $A487, $9161, $CDA0  ; d4
    DW $92ED, $7CB2, $3FED, $76AD  ; h4
    DW $F498, $DC8D, $253F, $A4D4  ; d5
    DW $F45F, $58D0, $96F8, $D38E  ; h5
    DW $BE90, $B388, $2956, $4BD7  ; d6
    DW $1DA9, $8F74, $E33E, $B79E  ; h6
    DW $653A, $5049, $7A64, $D723  ; d7
    DW $F759, $82A6, $6262, $5690  ; h7
    DW $6BB5, $6FA2, $C473, $7178  ; d8
    DW $AB05, $6AE6, $60BD, $625B  ; h8

; Piece 1: WhiteN
    DW $6573, $451B, $BAE9, $50A5  ; d1
    DW $3F46, $9DCA, $82C8, $0506  ; h1
    DW $935E, $F699, $A8D1, $BF33  ; d2
    DW $EAA1, $C346, $7B40, $CA8F  ; h2
    DW $2169, $AE6D, $5255, $046F  ; d3
    DW $BAA9, $5299, $19D1, $3315  ; h3
    DW $19FF, $DD86, $EBF5, $5F4D  ; d4
    DW $F897, $5693, $87F7, $200E  ; h4
    DW $A8DD, $1CD8, $E5E4, $37DC  ; d5
    DW $6BDC, $CDD3, $E48E, $B067  ; h5
    DW $BAF8, $31D4, $505B, $F7A1  ; d6
    DW $D7A0, $265B, $C790, $F5F5  ; h6
    DW $112D, $2903, $F557, $0C67  ; d7
    DW $D4EB, $39E4, $B9B7, $6780  ; h7
    DW $A5E1, $299D, $D997, $EB5A  ; d8
    DW $9ECC, $2BF0, $3448, $F7B5  ; h8

; Piece 2: WhiteB
    DW $F227, $BD31, $C3F0, $ABC6  ; d1
    DW $4CA0, $203A, $E791, $A7E9  ; h1
    DW $2A0B, $2241, $5B68, $13FC  ; d2
    DW $158A, $6047, $9B2F, $C3AF  ; h2
    DW $FFEE, $BB98, $1C74, $3744  ; d3
    DW $0E3B, $3B73, $D76C, $4BE9  ; h3
    DW $564B, $6A9D, $DBC0, $108C  ; d4
    DW $B4B2, $1197, $6D53, $F9DE  ; h4
    DW $B3CA, $0539, $1888, $FE31  ; d5
    DW $A40A, $45AD, $FAD7, $29DE  ; h5
    DW $FF83, $070C, $8AC6, $EBC9  ; d6
    DW $BC17, $68A5, $F0D7, $0368  ; h6
    DW $2214, $3E2E, $4032, $C3FB  ; d7
    DW $6C61, $C21F, $CB86, $8D1E  ; h7
    DW $4308, $E672, $50C2, $70E4  ; d8
    DW $F058, $70F4, $7D3F, $FA13  ; h8

; Piece 3: WhiteR
    DW $768E, $4288, $58DB, $0C45  ; d1
    DW $85AE, $C8FD, $EDE1, $EDCB  ; h1
    DW $8DA4, $8E1F, $5BB3, $79C1  ; d2
    DW $8646, $BB89, $7F58, $322A  ; h2
    DW $5922, $FA41, $66F5, $90D7  ; d3
    DW $B793, $AB72, $7E38, $972E  ; h3
    DW $2EC5, $7CF6, $E3DC, $28CF  ; d4
    DW $3B55, $F86D, $79C3, $9F6C  ; h4
    DW $BA7A, $A607, $149E, $FC4B  ; d5
    DW $513B, $F10A, $307A, $16A8  ; h5
    DW $6B7D, $3A05, $8AA7, $24D3  ; d6
    DW $00A7, $EC0E, $CBC5, $7230  ; h6
    DW $52A1, $F32D, $4058, $809F  ; d7
    DW $8E49, $F5C9, $9374, $127F  ; h7
    DW $67E4, $4242, $54C0, $F185  ; d8
    DW $8B4C, $C462, $0F2A, $1629  ; h8

; Piece 4: WhiteQ
    DW $40E5, $98BF, $4725, $BC37  ; d1
    DW $FB55, $3793, $5407, $0209  ; h1
    DW $C871, $35DF, $867E, $3F3E  ; d2
    DW $9859, $E347, $FE7A, $7E67  ; h2
    DW $A2B9, $E17F, $EC66, $F7E6  ; d3
    DW $979A, $262E, $5FED, $D011  ; h3
    DW $5266, $350A, $84D9, $E32F  ; d4
    DW $78C0, $173D, $B589, $7E4B  ; h4
    DW $E967, $34F6, $D4CE, $FD6D  ; d5
    DW $5510, $8755, $C65F, $D36C  ; h5
    DW $D822, $41B5, $5E7A, $4E7A  ; d6
    DW $322B, $F021, $568F, $931D  ; h6
    DW $70F1, $A593, $4843, $CD51  ; d7
    DW $04F0, $DEBC, $3D8A, $B691  ; h7
    DW $3913, $6C3C, $93CF, $47B1  ; d8
    DW $1263, $BC99, $BAF8, $038D  ; h8

; Piece 5: WhiteK
    DW $64FB, $3D9D, $20B1, $AFE6  ; d1
    DW $496C, $9591, $D3E2, $E4B1  ; h1
    DW $E95E, $2E86, $E7E3, $289E  ; d2
    DW $F773, $3C31, $0DCA, $A127  ; h2
    DW $3C74, $8A6A, $2ECB, $BE15  ; d3
    DW $CF70, $7714, $71FE, $D8F8  ; h3
    DW $4524, $7374, $A073, $481F  ; d4
    DW $883C, $6167, $8B9B, $57D2  ; h4
    DW $7171, $6FD0, $6806, $1873  ; d5
    DW $3FBB, $861C, $39C4, $81B5  ; h5
    DW $8B6A, $5B12, $9346, $5710  ; d6
    DW $F516, $E7D0, $35AA, $7084  ; h6
    DW $0816, $BB9A, $CB30, $BE17  ; d7
    DW $94F2, $D363, $5DD2, $C666  ; h7
    DW $0E82, $1553, $A388, $E2B1  ; d8
    DW $27D6, $CBF2, $CA65, $86B1  ; h8

; Piece 6: BlackP
    DW $0556, $62A1, $65C1, $F4B7  ; d1
    DW $6E64, $C858, $E41C, $ED22  ; h1
    DW $5B68, $5E16, $14D7, $CA90  ; d2
    DW $E577, $6284, $7E3B, $4FA8  ; h2
    DW $4E55, $87F5, $2BBD, $3DD6  ; d3
    DW $F2D1, $DA0B, $5CF0, $BC8B  ; h3
    DW $E9D7, $E000, $9DBF, $2144  ; d4
    DW $94EA, $ED66, $83FC, $41BD  ; h4
    DW $69CB, $F6DB, $7334, $8F04  ; d5
    DW $AE7B, $1828, $66D8, $9C49  ; h5
    DW $B573, $0A1B, $19A8, $82A0  ; d6
    DW $7822, $709F, $0FC0, $4421  ; h6
    DW $9903, $CB4D, $837D, $1F42  ; d7
    DW $3591, $1D3B, $A49E, $1783  ; h7
    DW $65B2, $0541, $883E, $ECED  ; d8
    DW $1877, $966C, $B610, $8D8A  ; h8

; Piece 7: BlackN
    DW $07F8, $B079, $A4EE, $5DEB  ; d1
    DW $927E, $83E0, $F525, $7C8C  ; h1
    DW $A8DB, $B8DB, $FEC6, $1E2F  ; d2
    DW $7C48, $3E31, $F4E7, $204F  ; h2
    DW $5854, $5731, $6127, $C1E6  ; d3
    DW $891C, $17EE, $2912, $A379  ; h3
    DW $64CC, $74F9, $39DA, $B6E4  ; d4
    DW $2D0E, $C3FE, $EB17, $EFD3  ; h4
    DW $22E4, $F8E6, $53E6, $D152  ; d5
    DW $B443, $5BD0, $C6B9, $00CD  ; h5
    DW $4FCF, $3892, $135E, $8DD8  ; d6
    DW $BAB4, $01D3, $52BF, $26C8  ; h6
    DW $0FF8, $38E4, $9D49, $0F8F  ; d7
    DW $CC46, $57FC, $D61C, $78EB  ; h7
    DW $241A, $F58E, $1A70, $D676  ; d8
    DW $FA07, $C64D, $6D78, $90EA  ; h8

; Piece 8: BlackB
    DW $AA34, $E3A9, $B061, $C35F  ; d1
    DW $ACEB, $C08A, $E73F, $B0CD  ; h1
    DW $5238, $BFBE, $CB9D, $BF8F  ; d2
    DW $03FD, $6237, $C158, $0B63  ; h2
    DW $BF9A, $FE72, $B17F, $2C1D  ; d3
    DW $B313, $97BA, $6898, $9A1D  ; h3
    DW $976D, $F42D, $08D2, $077B  ; d4
    DW $9BBF, $0172, $CC56, $D1F0  ; h4
    DW $C4C8, $8971, $EEF2, $5607  ; d5
    DW $F1D2, $DF23, $F7B1, $B410  ; h5
    DW $BEB0, $AEA4, $4EEA, $37A2  ; d6
    DW $C557, $1911, $6ED0, $A58F  ; h6
    DW $02BD, $7F37, $EE83, $14F8  ; d7
    DW $DDEB, $972E, $1E8D, $D753  ; h7
    DW $37D8, $D39A, $DD7F, $70A4  ; d8
    DW $062B, $9ED4, $7788, $5D19  ; h8

; Piece 9: BlackR
    DW $D7A0, $4E7A, $805A, $2C91  ; d1
    DW $BB65, $E822, $9AD6, $ACF0  ; h1
    DW $DA3C, $85C7, $F051, $CE39  ; d2
    DW $0EFA, $5D4D, $7846, $044F  ; h2
    DW $C56D, $C4E0, $B230, $4CFE  ; d3
    DW $9FBE, $19D6, $38AF, $0C67  ; h3
    DW $3527, $DC54, $94B4, $A05B  ; d4
    DW $8F9C, $A19A, $F749, $69C3  ; h4
    DW $3C1E, $4BCF, $7C58, $1C12  ; d5
    DW $A266, $7E28, $F3CD, $EC45  ; h5
    DW $23EF, $B9ED, $24F4, $0B0F  ; d6
    DW $3EC0, $BDDC, $4DA1, $FACD  ; h6
    DW $5DF7, $4CD6, $439B, $04FF  ; d7
    DW $72FB, $A60E, $252C, $E9E6  ; h7
    DW $E1F3, $FF00, $D7A8, $D865  ; d8
    DW $9E7A, $CE92, $68DB, $01FB  ; h8

; Piece 10: BlackQ
    DW $410E, $B2B8, $F9F7, $7EC1  ; d1
    DW $E3A1, $A7B6, $2EC5, $8079  ; h1
    DW $8652, $DA93, $8FB5, $985B  ; d2
    DW $65A6, $45EB, $B93F, $A28D  ; h2
    DW $FF94, $B391, $5286, $4931  ; d3
    DW $76ED, $6A92, $4E74, $992C  ; h3
    DW $A2CB, $9CB5, $75DA, $6184  ; d4
    DW $A5E4, $BE3D, $EB61, $C433  ; h4
    DW $4F36, $A6C5, $322F, $5D8A  ; d5
    DW $6DCE, $7146, $294C, $F33E  ; h5
    DW $EF41, $BB0D, $D863, $653D  ; d6
    DW $4FB4, $BAB7, $2018, $294F  ; h6
    DW $D58C, $88DB, $4C4D, $6056  ; d7
    DW $9D11, $7CB3, $CC8F, $7D5D  ; h7
    DW $570D, $276E, $2CAE, $4D7C  ; d8
    DW $56FC, $4C6D, $9EC1, $F909  ; h8

; Piece 11: BlackK
    DW $0092, $B3B9, $D151, $FF42  ; d1
    DW $5F03, $7657, $9C37, $1DC2  ; h1
    DW $771E, $CB8D, $929E, $BECF  ; d2
    DW $F940, $DF4D, $B04E, $4A9D  ; h2
    DW $83C4, $1909, $E637, $5C93  ; d3
    DW $2695, $35B7, $772E, $46BF  ; h3
    DW $F645, $EC7A, $7913, $B85D  ; d4
    DW $CDE3, $0F49, $8C47, $14C8  ; h4
    DW $9E9E, $9DBF, $21DE, $4554  ; d5
    DW $9AF5, $30CA, $1C9F, $35E7  ; h5
    DW $438E, $1EB0, $ED9B, $C4B4  ; d6
    DW $A1DE, $99FD, $39F4, $D0C1  ; h6
    DW $022B, $51DA, $A0CC, $8AC4  ; d7
    DW $3C8B, $35B7, $D3C6, $3A76  ; h7
    DW $39C9, $46BC, $BC5F, $3D67  ; d8
    DW $1490, $EFBF, $BE55, $47D8  ; h8

; ===========================================
; Side to Move Key (1 x 2 bytes)
; XOR when black to move
; ===========================================
ZOBRIST_SIDE:
    DW $D2D0

; ===========================================
; Castling Rights Keys (4 x 2 bytes)
; Index: 0=K, 1=Q, 2=k, 3=q
; ===========================================
ZOBRIST_CASTLE:
    DW $0905  ; WhiteKingside
    DW $1441  ; WhiteQueenside
    DW $1092  ; BlackKingside
    DW $BB78  ; BlackQueenside

; ===========================================
; En Passant File Keys (8 x 2 bytes)
; Index: 0=a-file, 7=h-file
; ===========================================
ZOBRIST_EP:
    DW $2D66  ; a-file
    DW $AC1B  ; b-file
    DW $9509  ; c-file
    DW $C434  ; d-file
    DW $42EA  ; e-file
    DW $AE3B  ; f-file
    DW $518F  ; g-file
    DW $80C8  ; h-file

; Total: 781 keys, 1562 bytes
