#!/usr/bin/env python3
"""
Generate Zobrist hash keys for chess transposition table.

Generates 16-bit pseudo-random keys for:
- 12 piece types x 64 squares = 768 keys
- Side to move = 1 key
- Castling rights (4 bits) = 4 keys
- En passant file (a-h) = 8 keys

Total: 781 keys x 2 bytes = 1,562 bytes

Output: Assembly file with .DW directives
"""

import random
import sys

# Seed for reproducibility - change to get different keys
SEED = 0x1802_CAFE

def generate_zobrist_asm():
    random.seed(SEED)

    print("; Zobrist hash keys for transposition table")
    print("; Generated by gen_zobrist.py")
    print("; Seed: 0x{:08X}".format(SEED))
    print(";")
    print("; Piece indices:")
    print(";   0-5:  White P, N, B, R, Q, K")
    print(";   6-11: Black P, N, B, R, Q, K")
    print(";")
    print("; Square indices: 0-63 (rank*8 + file)")
    print(";")
    print()

    # Piece-square keys: 12 pieces x 64 squares
    print("; ===========================================")
    print("; Piece-Square Keys (768 x 2 bytes = 1536 bytes)")
    print("; Access: ZOBRIST_PIECE_SQ + (piece_index * 128) + (square * 2)")
    print("; ===========================================")
    print("ZOBRIST_PIECE_SQ:")

    piece_names = ['WhiteP', 'WhiteN', 'WhiteB', 'WhiteR', 'WhiteQ', 'WhiteK',
                   'BlackP', 'BlackN', 'BlackB', 'BlackR', 'BlackQ', 'BlackK']

    for piece_idx, piece_name in enumerate(piece_names):
        print(f"; Piece {piece_idx}: {piece_name}")
        for sq in range(64):
            rank = sq // 8
            file = sq % 8
            key = random.randint(0, 0xFFFF)
            file_char = chr(ord('a') + file)
            rank_char = str(rank + 1)
            if sq % 4 == 0:
                print("    DW ", end="")
            print(f"${key:04X}", end="")
            if sq % 4 == 3:
                print(f"  ; {file_char}{rank_char}")
            else:
                print(", ", end="")
        print()

    # Side to move key
    print("; ===========================================")
    print("; Side to Move Key (1 x 2 bytes)")
    print("; XOR when black to move")
    print("; ===========================================")
    print("ZOBRIST_SIDE:")
    key = random.randint(0, 0xFFFF)
    print(f"    DW ${key:04X}")
    print()

    # Castling keys (4 separate keys for K, Q, k, q)
    print("; ===========================================")
    print("; Castling Rights Keys (4 x 2 bytes)")
    print("; Index: 0=K, 1=Q, 2=k, 3=q")
    print("; ===========================================")
    print("ZOBRIST_CASTLE:")
    castle_names = ['WhiteKingside', 'WhiteQueenside', 'BlackKingside', 'BlackQueenside']
    for i, name in enumerate(castle_names):
        key = random.randint(0, 0xFFFF)
        print(f"    DW ${key:04X}  ; {name}")
    print()

    # En passant file keys (8 files)
    print("; ===========================================")
    print("; En Passant File Keys (8 x 2 bytes)")
    print("; Index: 0=a-file, 7=h-file")
    print("; ===========================================")
    print("ZOBRIST_EP:")
    for file in range(8):
        key = random.randint(0, 0xFFFF)
        file_char = chr(ord('a') + file)
        print(f"    DW ${key:04X}  ; {file_char}-file")
    print()

    # Summary
    total_keys = 768 + 1 + 4 + 8
    total_bytes = total_keys * 2
    print(f"; Total: {total_keys} keys, {total_bytes} bytes")

if __name__ == "__main__":
    generate_zobrist_asm()
